# Generated by Django 4.1.13 on 2024-10-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='task',
        ),
        migrations.AddField(
            model_name='todo',
            name='email',
            field=models.EmailField(default='chhagan@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='todo',
            name='message',
            field=models.TextField(default='No message provided'),
        ),
    ]
